name: Github Pages Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  API_KEY: ${{secrets.API_KEY}}
  BASE_URL: ${{secrets.BASE_URL}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          base_branch: master
          branch: gh-pages
          folder: dist
